# 행렬의 성질

## 행렬의 부호
- 영 벡터가 아닌 모든 벡터 $x$ 에 대해 0보다 크면 행렬 $A$ 가 **양-정부호(positive definite)**이라고 한다.

$$
x^T A x > 0
$$

- 위의 식이 등호를 포함한다면 **양-준정부호(positive semi-definite)**이라고 한다.

$$
x^T A x \geq 0
$$

### <연습 문제 1>
다음 행렬을 양-정부호, 양-준정부호 혹은 아무것도 해당되지 않는지 판단하라.

$$
\begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix}
$$

(증명)

모든 벡터 $x^T = [x_1 \; x_2]$ 에 대해

$$
\begin{align} 
x^TA x 
&= \begin{bmatrix} x_1 & x_2 \end{bmatrix} \begin{bmatrix} 1&1\\1&1 \end{bmatrix}  \begin{bmatrix} x_1\\x_2 \end{bmatrix} \\
&= \begin{bmatrix} (x_1+x_2)&(x_1+x_2) \end{bmatrix} \begin{bmatrix} x_1\\x_2 \end{bmatrix} \\
&= {x_1}^2 + 2x_1x_2 + {x_2}^2 \\
&= (x_1 + x_2)^{2} 
\end{align}
$$

이 성립한다.

그리고 이 값은 제곱의 합으로 이루어졌으므로 $x_1 = x_2 = 0$ 인 경우를 제외하고는 항상 0보다 크다.

$$
(x_1 + x_2)^{2} > 0
$$

그러므로 다음 행렬은 양-정부호에 해당한다.

## 행렬의 크기
부호와 마찬가지로 행렬의 크기를 정의하는 것도 어렵다. 

하지만 하나의 행렬에 대해 하나의 실수를 대응시키는 개념의 **놈(norm), 대각합(trace), 행렬식(determinant)**이란 연산은 행렬의 크기와 비슷한 의미가 있다.

## 행렬 놈
$$
\Vert A \Vert_L = \left( \sum_{i=1}^M \sum_{j=1}^N |a_{ij}|^L \right)^{1/L}
$$

In [1]:
# 행렬의 크기 - 행렬 놈(norm)

A = (np.arange(9) - 4).reshape((3, 3))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [2]:
np.linalg.norm(A)

7.745966692414834

### <연습 문제 2>
행렬  $A(\text{A} \in \mathbf{R}^{N \times M})$ 의 놈의 제곱  $‖A‖^2$ 이 그 행렬을 이루는 행 벡터  $r_i$ 의 놈의 제곱의 합 또는 열 벡터  $c_i$ 의 놈의 제곱의 합과 같음을 증명하라.

$$
\Vert A \Vert^2 = \sum_{i=1}^N \Vert r_i \Vert^2  = \sum_{j=1}^M \Vert c_j \Vert^2
$$

(증명)
$$
\Vert A \Vert^2
= \sum_{i=1}^N \left( \sum_{j=1}^M a_{ij}^2 \right)
= \sum_{i=1}^N \Vert r_i \Vert^2 
\\
\Vert A \Vert^2
= \sum_{j=1}^M \left( \sum_{i=1}^N a_{ij}^2 \right)
= \sum_{j=1}^M \Vert c_i \Vert^2
$$

## 대각합
정방 행렬에 대해서만 정의되며 대각 원소들의 합으로 계산된다.

$$
\operatorname{tr}(A) = a_{11} + a_{22} + \dots + a_{NN}=\sum_{i=1}^{N} a_{ii}
$$

In [3]:
# 행령의 크기 - 대각합(trace)

np.trace(np.eye(3))

3.0

## 행렬식
$$
\det(A) = \sum_{i=1}^N \left\{ (-1)^{i+j_0}M_{i,j_0} \right\} a_{i,j_0} = \sum_{j=1}^N \left\{ (-1)^{i_0+j} M_{i_0,j} \right\} a_{i_0,j}
$$

가중치로 사용된  $M_{i,j}$ 는 마이너(minor, 소행렬식)라고 하며 정방 행렬  $A$  에서  $i$ 행과  $j$ 열을 지워서 얻어진 (원래의 행렬보다 크기가 1만큼 작은) 행렬의 행렬식이다.

마이너에  $(−1)^{i+j}$ 를 곱한 값을 코팩터(cofactor, 여인수)  $C_{i,j}$ 라고 한다.

$$
\det(A) = \sum_{i=1}^N C_{i,j_0} a_{i,j_0}  =  \sum_{j=1}^N C_{i_0,j} a_{i_0,j}
$$

- 행렬식의 성질
    - $\det(A^{T}) = \det(A)$
    - $\det(I) = 1$
    - $\det(AB) = \det(A)\det(B)$
    - $\det(A^{-1}) = \dfrac{1}{\det(A)}$

In [5]:
# 행렬의 크기 - 행렬식(determinant)
A = np.array([[1, 2], [3, 4]])
A
np.linalg.det(A)

-2.0000000000000004

## 부호와 크기의 관계

행렬의 양-정부호 성질과 대각합/행렬식은 다음과 같은 관계가 있다. 역은 일반적으로 성립하지 않는다.

- 행렬의 양-정부호(positive-definite)이면 대각합이 양수이다.
- 행렬의 양-정부호(positive-definite)이면 행렬식이 양수이다.
- 행렬의 양-준정부호(positive-semidefinite)이면 행렬식은 0이다.

### <연습 문제 5>
다음 행렬의 대각합과 행렬식을 구하고 위의 관계가 성립하는지 확인한다.

$$
A = \begin{bmatrix} 2 & -1 & 0\\-1&2&-1\\0&-1&2 \end{bmatrix} \\
B = \begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix} \\
C = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

In [6]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
B = np.array([[1, 1], [1, 1]])
C = np.array([[1, 2], [3, 4]])

In [7]:
np.trace(A)

6

In [8]:
np.linalg.det(A)

4.0

In [9]:
np.trace(B)

2

In [10]:
np.linalg.det(B)

0.0

In [11]:
np.trace(C)

5

In [12]:
np.linalg.det(C)

-2.0000000000000004

# 연립 방정식과 역행렬

## 역행렬
$A^{-1} A = A A^{-1} = I$

역행렬은 항상 존재하는 것이 아니라 원래의 행렬에 따라서는 존재하지 않을 수도 있다. 

역행렬이 존재하는 행렬을 가역행렬(invertible matrix), 정칙행렬regular matrix) 또는 비특이행렬(non-singular matrix)이라고 한다. 

반대로 역행렬이 존재하지 않는 행렬을 비가역행렬(non-invertible) 또는 특이행렬(singular matrix), 퇴화행렬(degenerate matrxi)이라고 한다.

## 역행렬의 성질
- $(A^{T})^{-1} = (A^{-1})^{T}$
- $(ABC)^{-1} = C^{-1} B^{-1} A^{-1}$
- $A^{-1} = \dfrac{1}{\det A} C^T = \dfrac{1}{\det A} 
\begin{bmatrix}
C_{1,1} &\cdots& C_{N, 1}\\
\vdots &\ddots &\vdots\\
C_{1,N} &\cdots &C_{N,N}\\
\end{bmatrix}$

임의의 정방행렬의 역행렬을 구할 수 있고 역행렬은 **행렬식이 0이 아닌 경우애만 존재**한다.

## NumPy를 사용한 역행렬 계산

In [13]:
A = np.array([[2, 3, -2], [3, 5, 6], [2, 4, 3]])
b = np.array([[-5], [12], [7]])
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.69230769,  1.30769231, -2.15384615],
       [-0.23076923, -0.76923077,  1.38461538],
       [-0.15384615,  0.15384615, -0.07692308]])

In [19]:
x = np.dot(Ainv, b)
x

array([[-2.84615385],
       [ 1.61538462],
       [ 2.07692308]])

In [21]:
np.dot(A, x) - b

array([[6.21724894e-15],
       [1.06581410e-14],
       [7.10542736e-15]])

###  <연습 문제 2>
보스턴 집값 문제를 선형 예측 모형  $Xw=ŷ$  로 풀었을 때의 가중치 벡터  w 를 구하라. 

행렬과 벡터 데이터는 다음과 같이 얻을 수 있다. 

여기에서는 문제를 간단하게 하기 위해 입력 데이터를 CRIM, NOX, RM, AGE의 4종류로 제한하였고 데이터도 4개만 사용하였다.

```
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]
```

In [22]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', NOX', 'RM', 'AGE'
b = y[:4]

In [23]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2.35172493e+01,  4.95752613e+01, -9.28388535e+01,
         7.19277399e+01],
       [ 5.96138349e+00,  6.66097478e+00, -2.68388003e+01,
         1.58431788e+01],
       [-2.19803095e-01, -8.06127089e-01,  1.99308607e+00,
        -9.57270077e-01],
       [-9.40782133e-03,  2.15240112e-02,  2.94704793e-02,
        -4.11681401e-02]])

In [24]:
w = np.dot(Ainv, b)
w

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [25]:
np.dot(A, w) - b

array([7.10542736e-15, 2.13162821e-14, 1.42108547e-14, 2.13162821e-14])

## 최소 자승 문제

In [29]:
A = np.array([[2, 3, -2], [3, 5, 6], [2, 4, 3], [0, 1, 2]])
A

array([[ 2,  3, -2],
       [ 3,  5,  6],
       [ 2,  4,  3],
       [ 0,  1,  2]])

In [30]:
b = np.array([[-5], [12], [7], [6]])
b

array([[-5],
       [12],
       [ 7],
       [ 6]])

In [31]:
Apinv = np.dot(np.linalg.inv(np.dot(A.T, A)), A.T) # 의사 역행렬
Apinv

array([[ 0.04509804,  0.75294118, -0.6745098 , -1.20196078],
       [ 0.15882353, -0.43529412,  0.49411765,  0.72352941],
       [-0.16862745,  0.14117647, -0.04313725, -0.02745098]])

In [32]:
x = np.dot(Apinv, b)
x

array([[-3.12352941],
       [ 1.78235294],
       [ 2.07058824]])

In [33]:
np.dot(A, x)

array([[-5.04117647],
       [11.96470588],
       [ 7.09411765],
       [ 5.92352941]])

### <연습 문제 3>
보스턴 집값 문제를 선형 예측 모형  $Xw=ŷ$  로 풀었을 때의 가중치 벡터  $w$ 를 최소 자승 방법으로 구하라. 

행렬과 벡터 데이터는 다음과 같이 얻을 수 있다.

```
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
```

In [35]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X
b = y

In [36]:
A.shape

(506, 13)

In [38]:
Apinv = np.dot(np.linalg.inv(np.dot(A.T, A)), A.T)
Apinv

array([[ 1.07451826e-04,  8.77916325e-05,  1.41714658e-04, ...,
         9.73867904e-05,  9.59182734e-05,  8.76715447e-05],
       [-4.72113488e-05, -1.21813358e-04, -1.63338555e-04, ...,
         9.25459456e-05,  8.62477809e-05,  1.03037440e-04],
       [-1.04962467e-03,  9.38480709e-05,  2.52898808e-04, ...,
         1.16621679e-04,  1.09508062e-04,  5.51053515e-07],
       ...,
       [-5.61140538e-04, -2.96148428e-04, -3.99979023e-04, ...,
         1.85433609e-03,  1.85210077e-03,  2.21855031e-03],
       [ 3.28586073e-06,  1.39152552e-06, -4.72593371e-06, ...,
        -1.20963339e-05, -1.21421770e-05, -6.39322420e-06],
       [-3.78907264e-04, -1.97458568e-04, -3.31131145e-04, ...,
        -7.96504098e-04, -7.64920375e-04, -7.76632690e-04]])

In [39]:
w = np.dot(Apinv, b)
w

array([-9.16297843e-02,  4.86751203e-02, -3.77930006e-03,  2.85636751e+00,
       -2.88077933e+00,  5.92521432e+00, -7.22447929e-03, -9.67995240e-01,
        1.70443393e-01, -9.38925373e-03, -3.92425680e-01,  1.49832102e-02,
       -4.16972624e-01])

In [42]:
np.dot(A, w) - b

array([ 5.10255504e+00,  2.90656965e+00, -3.46822060e+00, -3.68953357e+00,
       -6.63327593e+00, -3.40218947e+00, -1.36854483e+00, -7.99888377e+00,
       -5.41494160e+00, -6.41916512e-01,  4.33021710e+00,  1.51758950e+00,
       -2.03644591e+00,  2.68437695e-01,  2.32557495e+00,  2.21016397e-01,
       -1.56643938e+00,  8.63789599e-01, -4.45169411e+00,  6.22047741e-01,
       -2.41154475e-01, -7.70140928e-01,  2.68644962e+00,  7.65889808e-01,
        1.58299426e+00, -9.32147392e-02,  4.63980180e-02,  1.35276987e+00,
        3.47236648e+00,  2.39844184e+00,  2.20418339e-01,  4.77495299e+00,
       -2.61837041e+00,  1.92358719e+00,  1.34977199e+00,  3.65150254e+00,
        1.02428612e+00,  1.07505264e+00, -2.39963819e+00,  3.85369536e-01,
       -1.54346653e-01,  1.68231053e+00, -1.04179135e+00, -7.07347988e-01,
        7.56834476e-01,  8.42066210e-01, -8.82523606e-01,  1.01096024e+00,
       -5.72123497e+00, -3.39347927e+00,  5.59277311e-01,  2.19148936e+00,
        2.11397974e+00, -