### Reference
- http://www.numpy.org/
- http://aikorea.org/cs231n/python-numpy-tutorial/

### Install
- pip3 install numpy

### Make
- array
- reshape
- index
- 데이터 타입 변환
- 데이터 값 수정
- zeros
- ones
- eye
- like
- empty
- arange
- linespace, logspace
- rand, randn
- stack
- concatenate
- split
- sort

In [1]:
import numpy as np

##### array
- ndim : 행렬의 차원
- shape : 행렬의 모양 

In [2]:
# 1차원 배열 (vector)
array = np.array([0,1,2,3,4,5])
print(type(array))     
print(array)           # print에 출력하면 컴마가 없음.

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [3]:
# 2차원 배열 (3*1 matrix)
array = np.array([[0],[1],[2]]) 
print(array)

[[0]
 [1]
 [2]]


In [4]:
# 2차원 배열 (2*3 matrix)
array = np.array([
    [0,1,2],
    [3,4,5]
]) 
print(array)

[[0 1 2]
 [3 4 5]]


In [5]:
# 3차원 배열 (2*3*4 matrix)
array = np.array([
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]],
    [[0,1,2,3],
     [4,5,100,7],
     [8,9,10,11]]
]) 
print(array)
print(array.ndim, array.shape) # 바깥에서 안으로 모양을 나타낸다고 생각하면 편함

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]]
3 (2, 3, 4)


##### reshape
- 행렬의 모양을 바꿀수 있다.

In [6]:
na = np.array([1,2,3,4,5,6,7,8])
na.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
rna = np.reshape(na,(4,2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
# 전치행렬
rna.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

##### index
- 행렬의 특정 위치 데이터 값 가져오기
- 행렬 자르기

In [9]:
array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]]])

In [10]:
print(array[1][1][2])
print(array[1,1,2])

100
100


In [11]:
result = array[1:,1:,2:]
print(result)
print(result.ndim, result.shape)

[[[100   7]
  [ 10  11]]]
3 (1, 2, 2)


In [12]:
result = array[0][0]
print(result)
print(result.ndim, result.shape)

[0 1 2 3]
1 (4,)


##### 데이터 타입 변환

In [13]:
np.ones(5) # 그냥하면 실수형태

array([1., 1., 1., 1., 1.])

In [14]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

##### 데이터 값 수정

In [15]:
a = np.ones(10, dtype=int)
a[7:] = 5
a

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

In [16]:
a[3] = 4
a

array([1, 1, 1, 4, 1, 1, 1, 5, 5, 5])

##### zeros
- 행렬을 만들고 안에 0으로 채워 넣는다.

In [17]:
# 1차원
z = np.zeros(5)
print(z)
print(z.ndim, z.shape)

[0. 0. 0. 0. 0.]
1 (5,)


In [18]:
# 2차원 (2*3)
z = np.zeros([2,3])
print(z)
print(z.ndim, z.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
2 (2, 3)


In [19]:
# 3차원 (2*3*4)
z = np.zeros([2,3,4])
print(z)
print(z.ndim, z.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


##### ones
- 행렬을 만들고 안에 1을 채워 넣는다.

In [20]:
# 3차원 (2*3*4)
o = np.ones([2,3,4])
print(o)
print(o.ndim, o.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


##### eye
- 단위 행렬 데이터를 만든다.

In [21]:
# 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### like
- 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀수 있다.

In [22]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
ls = np.ones_like(z)
print(ls)
print(ls.ndim, ls.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


In [24]:
o

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
ls = np.zeros_like(o)
print(ls)
print(ls.ndim, ls.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


##### empty
- 빈행렬을 만든다.
- 실제로는 빈데이터가 아니라 더미 데이터가 들어간다
- 사용빈도 낮음

In [26]:
a = np.empty([5,5])
print(a)

[[0.00000000e+000 0.00000000e+000 1.03753786e-322 0.00000000e+000
  2.12199579e-314]
 [5.02034658e+175 1.90187520e+185 3.37933889e-057 1.70287905e+160
  1.68675348e+160]
 [1.47763641e+248 1.16096346e-028 7.69165785e+218 1.35617292e+248
  6.84359008e+169]
 [2.79048598e+179 8.97365842e-067 6.28201027e+174 4.26034043e-096
  6.32299154e+233]
 [6.48224638e+170 5.22411352e+257 5.74020278e+180 8.37174974e-144
  1.41529402e+161]]


##### arange
- range와 같다.
- **하지만 큰데이터에서 range 보다 속도가 빠르다**

In [27]:
# range와 arange의 속도 비교
size = int(1E6) # E : exponential --> 1000000
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2

393 ms ± 30.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
226 ms ± 6.76 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [30]:
np.arange(2,10,3)

array([2, 5, 8])

In [31]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

##### linspace, logspace

In [32]:
np.linspace(0, 100, 5) # 0~100까지 5등분해서 나타냄

array([  0.,  25.,  50.,  75., 100.])

In [33]:
# log10(x)=2, log10(x)=2.5, log10(x)=3
# 10**2, 10**2.5, 10**3
print(np.logspace(2, 4, 3))
print(np.logspace(2, 3, 3))

[  100.  1000. 10000.]
[ 100.          316.22776602 1000.        ]


In [34]:
10**2, 10**2.5, 10**3, 10**4

(100, 316.22776601683796, 1000, 10000)

##### random
- seed # 기준값? : 같은 난수를 발생하고 싶으면 설정하고 계속 다른 난수를 발생하고 싶으면 설정하지 않음
- rand (uniform)
- randn (gaussian)
- randint (uniform)
- shuffle
- choice

In [35]:
np.random.seed(0)   # seed값이 같으면 똑같은 난수가 발생
rd = np.random.rand(10)   # uniform 으로 난수 발생  (균등분포)
rdn = np.random.randn(10) # gaussian 으로 난수 발생 (정규분포 - 0에 가까운수가 많이 나옴)
print(rd)
print(rdn)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [36]:
# e-01 -> (10**-1)
np.random.seed(1)
rd = np.random.rand(4)
rdn = np.random.randn(4)
print(rd)
print(rdn)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
[-0.52817175 -1.07296862  0.86540763 -2.3015387 ]


In [37]:
r = np.random.rand(2,3,4)
print(r)

[[[0.41919451 0.6852195  0.20445225 0.87811744]
  [0.02738759 0.67046751 0.4173048  0.55868983]
  [0.14038694 0.19810149 0.80074457 0.96826158]]

 [[0.31342418 0.69232262 0.87638915 0.89460666]
  [0.08504421 0.03905478 0.16983042 0.8781425 ]
  [0.09834683 0.42110763 0.95788953 0.53316528]]]


In [38]:
r = np.random.randint(0,10,[3,3])  # (start, end-1, shape) 중복허용
print(r)

[[4 8 1]
 [4 0 3]
 [9 2 0]]


In [39]:
r = np.random.randint(10, size=[3,4])
r

array([[4, 9, 2, 7],
       [7, 9, 8, 6],
       [9, 3, 7, 7]])

In [41]:
# shuffle로 데이터의 순서를 바꿀수 있다. 맨 바깥 차원 사이에서만 shuffle이 일어남(행끼리만 섞임)
np.random.shuffle(r)
r

array([[9, 3, 7, 7],
       [7, 9, 8, 6],
       [4, 9, 2, 7]])

In [42]:
# 행,열 상관없이 썪는법
np.random.shuffle(r.flat)
r

array([[9, 7, 2, 9],
       [7, 3, 6, 7],
       [9, 4, 8, 7]])

In [43]:
# p의 확률로 range(5)를 10개 추출
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 확률은 다 더해서 1이 되어야 함.

array([3, 2, 3, 3, 3, 0, 3, 3, 3, 3])

In [44]:
# unique로 데이터의 유일한 값에 대한 리스트와 값의 갯수를 구할수 있다
index, count = np.unique(r, return_counts=True)
index, count

(array([2, 3, 4, 6, 7, 8, 9]), array([1, 1, 1, 1, 4, 1, 3]))

##### stack
- 행렬을 쌓는것과 같이 합치는 방법

In [45]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)


In [48]:
na3 = np.stack((na1, na2))   # 기본적으로 vertical로 쌓임 (axis=0)
print(na3, na3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [49]:
na4 = np.stack((na1, na2), axis=1) 
print(na4, na4.shape)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] (6, 2)


In [50]:
# practice 1
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])    
ls

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [51]:
# 수직으로 합치기
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [52]:
# 수평으로 합치기. 하지만 리스트가 된다
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [53]:
# 수평으로 합치기  
data = [list(range(7)[i:i+3]) for i in range(5) ] 
print(data)
np.stack(data, axis=1)  # axis = -1 과 1 같습니다.

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [54]:
# practice 2
np.arange(5)[:, np.newaxis]  # 계속 새로운 축을 생성

array([[0],
       [1],
       [2],
       [3],
       [4]])

##### concatenate (결합)
- 가로 결합은 열의 갯수가 같아야 한다. axis=0
- 세로 결합은 행의 갯수가 같아야 한다. axis=1

In [55]:
r1 = np.random.randint(10, size=(2,3))  # 0~9
print(r1)

[[5 7 8]
 [4 4 7]]


In [56]:
r2 = np.random.randint(10, size=(3,2))
print(r2)

[[7 4]
 [9 0]
 [2 0]]


In [57]:
r3 = np.random.randint(10, size=(3,3))
print(r3)

[[7 1 7]
 [9 8 4]
 [0 1 9]]


In [58]:
# 가로 결합
np.concatenate([r1, r3], axis=0)

array([[5, 7, 8],
       [4, 4, 7],
       [7, 1, 7],
       [9, 8, 4],
       [0, 1, 9]])

In [59]:
# 세로 결합
np.concatenate([r2, r3], axis=1)

array([[7, 4, 7, 1, 7],
       [9, 0, 9, 8, 4],
       [2, 0, 0, 1, 9]])

##### split

In [60]:
r = np.arange(5,20)
r

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
r1 = np.split(r, [5]) # 앞에서 index 5번째 앞에서 자른다.
r1

[array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [62]:
# r1에는 나눈 데이터의 첫번째 데이터가 r2에는 나눈 데이터의 두번째 데이터가 들어간다
r1, r2 = np.split(r, [5]) 
r1, r2

(array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [63]:
r1, r2, r3, r4, r5 = np.split(r, [2,4,6,8]) # index값 2,4,6,8 앞에서 나눠 5개의 array 데이터가 생성된다.
r1, r2, r3, r4, r5

(array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12]),
 array([13, 14, 15, 16, 17, 18, 19]))

##### vsplit/hsplit
- 행렬을 수직, 수평으로 나눈다

In [64]:
r = np.random.randint(10, size=(4,6))
r

array([[8, 2, 3, 1, 2, 7],
       [2, 6, 0, 9, 2, 6],
       [6, 2, 7, 7, 0, 6],
       [5, 1, 4, 6, 0, 6]])

In [65]:
# 수평으로 2개씩 자름
r1, r2 = np.vsplit(r, [2]) # 가르킨 index앞에서 잘림.
print(r1, end="\n""\n")
print(r2)

[[8 2 3 1 2 7]
 [2 6 0 9 2 6]]

[[6 2 7 7 0 6]
 [5 1 4 6 0 6]]


In [ ]:
# 수평으로 3개씩 자름 해봐~~~

In [66]:
# 수직으로 3개씩 자름
r1, r2 = np.hsplit(r, [3])
print(r1, end='\n''\n')
print(r2)

[[8 2 3]
 [2 6 0]
 [6 2 7]
 [5 1 4]]

[[1 2 7]
 [9 2 6]
 [7 0 6]
 [6 0 6]]


In [67]:
# 수직으로 2개씩 자름
r1, r2, r3 = np.hsplit(r, [2,4])
print(r1, end='\n''\n')
print(r2, end='\n''\n')
print(r3)

[[8 2]
 [2 6]
 [6 2]
 [5 1]]

[[3 1]
 [0 9]
 [7 7]
 [4 6]]

[[2 7]
 [2 6]
 [0 6]
 [0 6]]


##### sort

In [68]:
r1 = np.random.randint(10, size=(3,3))
print(r1)

[[5 1 2]
 [1 5 4]
 [0 7 8]]


In [69]:
# 가로로 sorting
r1.sort() # axis -1과 1은 같은 동작을 한다
r1

array([[1, 2, 5],
       [1, 4, 5],
       [0, 7, 8]])

In [70]:
# 세로로 sorting
r1.sort(axis=0) 
r1

array([[0, 2, 5],
       [1, 4, 5],
       [1, 7, 8]])

In [71]:
# 문제
# 1~9까지의 숫자가 들어가는 3*3 행렬을 만드세요
# 만든 행렬을 무작위로 섞으세요
a = np.arange(1,10).reshape(3,3).T
np.random.shuffle(a)
a

array([[1, 4, 7],
       [3, 6, 9],
       [2, 5, 8]])

In [72]:
a = np.arange(1,10)
np.random.shuffle(a)
a.reshape(3,3)

array([[9, 6, 3],
       [5, 7, 4],
       [2, 1, 8]])

##### np.c_  /  np.r_

In [96]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])