### Datatype
- boolean : bool
- integer : int64
- float : float64
- byte String : S24
- unicode String : U24

In [1]:
import numpy as np

In [2]:
na = np.array([True, False])  
na.dtype

dtype('bool')

In [3]:
na = np.array([1, 2, 3])   # 한번에 한가지 데이터타입만 사용가능
na.dtype

dtype('int64')

In [4]:
na = np.array([1.0, 2.0, 3.0])
na.dtype

dtype('float64')

##### change datatype

In [5]:
na = np.array([-1.0, 0.0, 1.0, 2.2, 3.8])
print(na)

na = na.astype('int64')
print(na)

na = na.astype('bool')
print(na)

na = na.astype('S24')
print(na)

na = na.astype('U24')
print(na)

[-1.   0.   1.   2.2  3.8]
[-1  0  1  2  3]
[ True False  True  True  True]
[b'True' b'False' b'True' b'True' b'True']
['True' 'False' 'True' 'True' 'True']


##### 5~10까지 랜덤한 숫자가 들어있는 5*5 행렬 만들기

In [7]:
# 1.  
na = np.random.rand(5,5)
print(na)

[[0.96592487 0.08343522 0.54017096 0.97069635 0.54344663]
 [0.11935112 0.94379807 0.87298343 0.46422832 0.2976807 ]
 [0.18970584 0.31281618 0.3924082  0.18093057 0.47253386]
 [0.63641209 0.34573242 0.34769268 0.41822795 0.30584009]
 [0.11032719 0.53813538 0.05605993 0.86764061 0.4442148 ]]


In [8]:
na*6+5

array([[10.7955492 ,  5.50061132,  8.24102575, 10.82417807,  8.26067976],
       [ 5.71610671, 10.6627884 , 10.23790055,  7.78536989,  6.7860842 ],
       [ 6.13823506,  6.87689706,  7.35444923,  6.08558345,  7.83520317],
       [ 8.81847256,  7.07439453,  7.08615609,  7.50936767,  6.83504055],
       [ 5.66196312,  8.22881227,  5.33635959, 10.20584365,  7.66528879]])

In [9]:
na = (na*6+5).astype('int64')
print(na)

[[10  5  8 10  8]
 [ 5 10 10  7  6]
 [ 6  6  7  6  7]
 [ 8  7  7  7  6]
 [ 5  8  5 10  7]]


In [10]:
# 2. 간단한 방법
na2 = np.random.randint(5, 11, size=(5, 5))
print(na2)

[[10  8  7  7  8]
 [ 9  9  6  6 10]
 [ 7  8 10  8  8]
 [ 5  5  5  9  6]
 [10 10  7 10  7]]
